env:
  node: true
  es2021: true

extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jest/recommended
  - airbnb-base

parser: '@typescript-eslint/parser'

parserOptions:
  ecmaVersion: 12
  sourceType: module

plugins:
  - typescript
  - '@typescript-eslint'
  - jest

ignorePatterns:
  - dist
  - node_modules

rules:
  indent: [error, 4]
  linebreak-style: [error, unix]
  quotes: [error, single]
  semi: [error, never]
  import/extensions:
    - error
    - ignorePackages
    - ts: never
      js: always
